name: clean_pro_user
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:

  carousel_slider: ^5.0.0
  curved_navigation_bar: ^1.0.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_platform_widgets: ^7.0.1
 
  flutter_riverpod: ^2.5.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^4.2.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  geocoding: ^3.0.0
  get: ^4.6.6
  google_fonts: ^6.2.1
  http: ^1.2.2
  persistent_bottom_nav_bar: ^6.2.1
  pinput: ^5.0.0
  riverpod: ^2.5.1
  salomon_bottom_bar: ^3.3.2
  shimmer: ^3.0.0
  step_progress_indicator: ^1.0.2
  url_launcher: ^6.3.0


dev_dependencies:
  
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/icons/
    - assets/carosel_images/
  
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins.medium.ttf
          weight: 500
    - family: open-sans
      fonts:
        - asset: assets/fonts/open-sans.regular.ttf
          weight: 500
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 500
    - family: Montserrat_light
      fonts:
        - asset: assets/fonts/Montserrat-VariableFont_wght.ttf
          weight: 200
